version: 2
updates:
  - package-ecosystem: gomod
    directory: /golang
    schedule:
      interval: cron
      cronjob: "0 7,19 * * *"
      timezone: Australia/Sydney
    cooldown:
      semver-patch-days: 3
