package modelsync

import (
	"bytes"
	"fmt"
	"path"
	"strings"
)

// generatedProvider describes how the default rules generator reads one
// first-party provider's prices from OpenRouter's upstream endpoints.
type generatedProvider struct {
	name    string
	prefix  string
	modelID string
	// tiers maps a conventional endpoint provider_value to the OpenRouter
	// endpoint tags, in preference order, that publish its price.
	tiers []generatedTier
	// skip lists OpenRouter IDs that are not model IDs of the provider's own
	// API (OpenRouter presets, media-only models, completions-only models).
	skip []string
}

type generatedTier struct {
	tier string
	tags []string
}

var generatedProviders = []generatedProvider{
	{
		name: "openai", prefix: "openai/", modelID: ModelIDVerbatim,
		tiers: []generatedTier{
			{tier: "flex", tags: []string{"openai/flex"}},
			{tier: "default", tags: []string{"openai", "openai/default"}},
			{tier: "priority", tags: []string{"openai/fast"}},
		},
		skip: []string{"openai/*-high", "openai/*image*", "openai/*audio*", "openai/gpt-chat-latest", "openai/gpt-3.5-turbo-instruct"},
	},
	{
		name: "anthropic", prefix: "anthropic/", modelID: ModelIDDotsToDashes,
		tiers: []generatedTier{
			{tier: "standard_only", tags: []string{"anthropic"}},
			{tier: "auto", tags: []string{"anthropic"}},
		},
	},
}

// exaRules are maintained by hand: OpenRouter does not list Exa.
const exaRules = `  exa:
    prefix: exa/
    model_id: verbatim
    models:
      # Exa's chat-completions model "exa" is its /answer API, billed per
      # request (https://exa.ai/pricing). Exa reports each call's actual cost.
      exa/exa:
        model: exa
        prices:
          standard:
            input_per_million: "0"
            output_per_million: "0"
            cache_read_per_million: "0"
            cache_write_per_million: "0"
            per_request: "0.005"
`

// GenerateDefaultRules renders the built-in rules file from an OpenRouter
// Document. Direct prices are the first-party upstream endpoint prices
// OpenRouter publishes (for example its "openai/flex" or "anthropic"
// endpoint), which are those providers' list prices. A direct route's context
// window is capped at the first long-prompt price threshold so its base price
// always applies. Models a provider's own API no longer serves have no
// first-party endpoint and are left out.
func GenerateDefaultRules(document Document) ([]byte, error) {
	if err := document.Validate(); err != nil {
		return nil, err
	}
	var out bytes.Buffer
	fmt.Fprintf(&out, `# Built-in model-sync rules, compiled into the worker binary and therefore
# shipped in its image. Operators override them at runtime with
# model_sync.rules files; a later file overrides an earlier one field by
# field, and prices merge per tier.
#
# Every model is named by its OpenRouter ID. Direct prices are keyed by the
# endpoint's service_classes provider_value.
#
# GENERATED by "go run ./tools/modelsyncdefaults" from the first-party
# upstream endpoint prices OpenRouter published at %s.
# Review the diff before committing; the Exa section is maintained by hand in
# golang/internal/modelsync/generate.go.
version: %s

providers:
`, document.FetchedAt.UTC().Format("2006-01-02T15:04:05Z"), RulesVersion)
	for _, provider := range generatedProviders {
		fmt.Fprintf(&out, "  %s:\n    prefix: %s\n    model_id: %s\n    models:\n", provider.name, provider.prefix, provider.modelID)
		count := 0
		for _, model := range document.Models {
			if !strings.HasPrefix(model.ID, provider.prefix) || skipped(provider.skip, model.ID) {
				continue
			}
			rendered, ok, err := renderGeneratedModel(provider, model)
			if err != nil {
				return nil, fmt.Errorf("model %q: %w", model.ID, err)
			}
			if ok {
				out.WriteString(rendered)
				count++
			}
		}
		if count == 0 {
			return nil, fmt.Errorf("no %s models have first-party endpoints", provider.name)
		}
	}
	out.WriteString(exaRules)
	rendered := out.Bytes()
	parsed, err := ParseRules(rendered)
	if err != nil {
		return nil, err
	}
	if _, err := MergeRules(parsed); err != nil {
		return nil, err
	}
	return rendered, nil
}

func skipped(patterns []string, id string) bool {
	for _, pattern := range patterns {
		if matched, _ := path.Match(pattern, id); matched {
			return true
		}
	}
	return false
}

func renderGeneratedModel(provider generatedProvider, model Model) (string, bool, error) {
	byTag := make(map[string]Endpoint, len(model.Endpoints))
	for _, endpoint := range model.Endpoints {
		byTag[endpoint.Tag] = endpoint
	}
	type tierPrice struct {
		tier     string
		endpoint Endpoint
	}
	priced := make([]tierPrice, 0, len(provider.tiers))
	for _, tier := range provider.tiers {
		for _, tag := range tier.tags {
			if endpoint, ok := byTag[tag]; ok {
				priced = append(priced, tierPrice{tier: tier.tier, endpoint: endpoint})
				break
			}
		}
	}
	if len(priced) == 0 {
		return "", false, nil
	}
	contextTokens, outputTokens := model.ContextLength, model.MaxCompletionTokens
	for _, value := range priced {
		contextTokens = minPositive(contextTokens, value.endpoint.ContextLength)
		outputTokens = minPositive(outputTokens, value.endpoint.MaxCompletionTokens)
		if overrides := value.endpoint.Pricing.Overrides; len(overrides) > 0 {
			contextTokens = minPositive(contextTokens, overrides[0].MinPromptTokens)
		}
	}
	var out strings.Builder
	fmt.Fprintf(&out, "      %s:\n", model.ID)
	if contextTokens > 0 {
		fmt.Fprintf(&out, "        context_tokens: %d\n", contextTokens)
	}
	if outputTokens > 0 {
		fmt.Fprintf(&out, "        output_tokens: %d\n", outputTokens)
	}
	out.WriteString("        prices:\n")
	for _, value := range priced {
		prices := value.endpoint.Pricing
		cacheRead := prices.InputCacheRead
		if cacheRead == "" {
			cacheRead = prices.Prompt
		}
		// The adapters never request a one-hour cache, so the five-minute
		// write price applies; an unlisted write price is not billed.
		cacheWrite := prices.InputCacheWrite
		if cacheWrite == "" {
			cacheWrite = "0"
		}
		request := prices.Request
		if request == "" {
			request = "0"
		}
		fields := []struct{ name, perToken string }{
			{"input_per_million", prices.Prompt}, {"output_per_million", prices.Completion},
			{"cache_read_per_million", cacheRead}, {"cache_write_per_million", cacheWrite},
		}
		fmt.Fprintf(&out, "          %s:\n", value.tier)
		for _, field := range fields {
			converted, err := perMillion(field.perToken)
			if err != nil {
				return "", false, fmt.Errorf("%s %s: %w", value.tier, field.name, err)
			}
			fmt.Fprintf(&out, "            %s: %q\n", field.name, converted.CanonicalString())
		}
		fmt.Fprintf(&out, "            per_request: %q\n", request)
	}
	return out.String(), true, nil
}
